<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Domain\Entities\TESTE\**" />
    <Compile Remove="Expcetions\**" />
    <EmbeddedResource Remove="Domain\Entities\TESTE\**" />
    <EmbeddedResource Remove="Expcetions\**" />
    <None Remove="Domain\Entities\TESTE\**" />
    <None Remove="Expcetions\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Domain\Enums\SearchStatusEnum.cs" />
    <Compile Remove="DTOs\Requests\ResponseSearch.cs" />
    <Compile Remove="Interfaces\Services\DashboardService.cs" />
    <Compile Remove="Interfaces\Services\_dashboardRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.5.0" />
    <PackageReference Include="Ulid" Version="1.4.1" />
  </ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
  <ItemGroup>
    <Folder Include="InterfacesAdmin\Repositories\" />
  </ItemGroup>

</Project>
