// <auto-generated />
using System;
using Mercado.Craibas.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mercado.Craibas.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705234440_atualizeDateTime")]
    partial class atualizeDateTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Id_User_Customer")
                        .HasColumnType("int");

                    b.Property<int?>("Id_User_Delivery")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferencePoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Road")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool?>("Standard")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Supplement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id_User_Customer");

                    b.HasIndex("Id_User_Delivery")
                        .IsUnique()
                        .HasFilter("[Id_User_Delivery] IS NOT NULL");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_User_Customer")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id_User_Customer");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Cart_Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Cart")
                        .HasColumnType("int");

                    b.Property<int>("Id_Product")
                        .HasColumnType("int");

                    b.Property<int>("Id_Variante")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Variante_ProductsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_Cart");

                    b.HasIndex("Id_Product");

                    b.HasIndex("Variante_ProductsId");

                    b.ToTable("Cart_Item", (string)null);
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Cupom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Cod_Cupom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_Start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriotion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("Discont")
                        .HasColumnType("float");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Minimum_Value")
                        .HasColumnType("float");

                    b.Property<string>("Name_Cupom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cupom", (string)null);
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Customize_Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Dark")
                        .HasColumnType("bit");

                    b.Property<string>("Global_Site_Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Id_User_Admin")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id_User_Admin")
                        .IsUnique();

                    b.ToTable("Customize_Admin", (string)null);
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Customize_Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Global_Site_Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Id_User_Customer")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id_User_Customer")
                        .IsUnique();

                    b.ToTable("Customize_Cliente", (string)null);
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Imagens_Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Product")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url_Imagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Product");

                    b.ToTable("Imagens_Products", (string)null);
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.OrderLineItens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Discont")
                        .HasColumnType("float");

                    b.Property<int>("Id_Order")
                        .HasColumnType("int");

                    b.Property<int>("Id_Product")
                        .HasColumnType("int");

                    b.Property<int>("Id_Variante_Product")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name_Product")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("Origin_Price")
                        .HasColumnType("float");

                    b.Property<double>("Price_Unit")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Total_Price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Variante_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Variante_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Variante_Value")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Order");

                    b.HasIndex("Id_Product");

                    b.ToTable("OrderLineItens", (string)null);
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Delivery_Commission")
                        .HasColumnType("float");

                    b.Property<double>("Discont")
                        .HasColumnType("float");

                    b.Property<double>("Discont_Percentage")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Estimated_Delivery_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Address")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Cupom")
                        .HasColumnType("int");

                    b.Property<int?>("Id_User_Customer")
                        .HasColumnType("int");

                    b.Property<int?>("Id_User_Delivery")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Number_Order")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Order_Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payment_terms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status_Pay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total_Value_Order")
                        .HasColumnType("float");

                    b.Property<string>("Tracking_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id_Address");

                    b.HasIndex("Id_Cupom");

                    b.HasIndex("Id_User_Customer");

                    b.HasIndex("Id_User_Delivery");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Badge")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cod_Cupom")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CountSold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Featured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("FreeShipping")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Id_Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double>("Origin_Price")
                        .HasColumnType("float");

                    b.Property<double>("Price_Unit")
                        .HasColumnType("float");

                    b.Property<double>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("ReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Total_Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("installments")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Id_Category");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Product_Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Product_Category", (string)null);
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Id_Product")
                        .HasColumnType("int");

                    b.Property<int>("Id_User_Customer")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ranting")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id_Product");

                    b.HasIndex("Id_User_Customer");

                    b.ToTable("Rating", (string)null);
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.User_Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Phone")
                        .HasColumnType("float");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User_Admin", (string)null);
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.User_Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Phone")
                        .HasColumnType("float");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User_Customer", (string)null);
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.User_Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("CommissionDelivers")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Phone")
                        .HasColumnType("float");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Transport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User_Delivery", (string)null);
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Variante_Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Product")
                        .HasColumnType("int");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("Price_Modifier")
                        .HasColumnType("float");

                    b.Property<int>("Stoke")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Product");

                    b.ToTable("Variante_Products", (string)null);
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Address", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.User_Customer", "User_Customer")
                        .WithMany("Address")
                        .HasForeignKey("Id_User_Customer")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.User_Delivery", "User_Delivery")
                        .WithOne("Address")
                        .HasForeignKey("Baldan.Pricing.Application.Domain.Entities.Address", "Id_User_Delivery")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User_Customer");

                    b.Navigation("User_Delivery");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Cart", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.User_Customer", "User_Customer")
                        .WithMany("Carts")
                        .HasForeignKey("Id_User_Customer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User_Customer");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Cart_Item", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.Cart", "Cart")
                        .WithMany("Cart_Items")
                        .HasForeignKey("Id_Cart")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.Product", "Product")
                        .WithMany("Cart_Items")
                        .HasForeignKey("Id_Product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.Variante_Products", "Variante_Products")
                        .WithMany("Cart_Items")
                        .HasForeignKey("Variante_ProductsId");

                    b.Navigation("Cart");

                    b.Navigation("Product");

                    b.Navigation("Variante_Products");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Customize_Admin", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.User_Admin", "User_Admin")
                        .WithOne("Customize_Admin")
                        .HasForeignKey("Baldan.Pricing.Application.Domain.Entities.Customize_Admin", "Id_User_Admin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User_Admin");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Customize_Cliente", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.User_Customer", "User_Customer")
                        .WithOne("Customize_Cliente")
                        .HasForeignKey("Baldan.Pricing.Application.Domain.Entities.Customize_Cliente", "Id_User_Customer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User_Customer");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Imagens_Products", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.Product", "Product")
                        .WithMany("Imagens_Products")
                        .HasForeignKey("Id_Product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.OrderLineItens", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.Orders", "Orders")
                        .WithMany("OrderLineItens")
                        .HasForeignKey("Id_Order")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.Product", "Product")
                        .WithMany("OrderLineItens")
                        .HasForeignKey("Id_Product")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Orders", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("Id_Address")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.Cupom", "Cupom")
                        .WithMany("Orders")
                        .HasForeignKey("Id_Cupom")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.User_Customer", "User_Customer")
                        .WithMany("Orders")
                        .HasForeignKey("Id_User_Customer")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.User_Delivery", "User_Delivery")
                        .WithMany("Orders")
                        .HasForeignKey("Id_User_Delivery")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("Cupom");

                    b.Navigation("User_Customer");

                    b.Navigation("User_Delivery");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Product", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.Product_Category", "Product_Category")
                        .WithMany("Product")
                        .HasForeignKey("Id_Category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product_Category");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Rating", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.Product", "Product")
                        .WithMany("Ratings")
                        .HasForeignKey("Id_Product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.User_Customer", "User_Customer")
                        .WithMany("Ratings")
                        .HasForeignKey("Id_User_Customer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User_Customer");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Variante_Products", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Domain.Entities.Product", "Product")
                        .WithMany("Variante_Products")
                        .HasForeignKey("Id_Product")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Cart", b =>
                {
                    b.Navigation("Cart_Items");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Cupom", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Orders", b =>
                {
                    b.Navigation("OrderLineItens");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Product", b =>
                {
                    b.Navigation("Cart_Items");

                    b.Navigation("Imagens_Products");

                    b.Navigation("OrderLineItens");

                    b.Navigation("Ratings");

                    b.Navigation("Variante_Products");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Product_Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.User_Admin", b =>
                {
                    b.Navigation("Customize_Admin");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.User_Customer", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Carts");

                    b.Navigation("Customize_Cliente");

                    b.Navigation("Orders");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.User_Delivery", b =>
                {
                    b.Navigation("Address");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Domain.Entities.Variante_Products", b =>
                {
                    b.Navigation("Cart_Items");
                });
#pragma warning restore 612, 618
        }
    }
}
