// <auto-generated />
using System;
using Mercado.Craibas.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mercado.Craibas.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.City", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.Family", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Family");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.Manufacturer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Manufacturer");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.OwnerProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<int>("Derivation")
                        .HasColumnType("int");

                    b.Property<string>("FamilyId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vertical")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("OwnerProducts");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.Period", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PeriodStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartdDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TwoMonthPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Period");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Profiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.Search", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerProductId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<string>("PeriodId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<string>("SearchStatusId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<string>("ThirdProductId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerProductId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("SearchStatusId");

                    b.HasIndex("ThirdProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Search");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.SearchStatus", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SearchStatus");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.State", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.SurveyEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<string>("Attachment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PeriodId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<string>("PriceIncludingTax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ResalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SearchId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<string>("ShippingIncluded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("SearchId");

                    b.ToTable("SurveyEntry");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.ThirdProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManufacturerId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerProductId")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("OwnerProductId")
                        .IsUnique();

                    b.ToTable("ThirdProduct");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profileid")
                        .IsRequired()
                        .HasColumnType("char(26)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Profileid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.City", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Models.Entities.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.OwnerProduct", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Models.Entities.Family", "Family")
                        .WithMany("OwnerProducts")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.Search", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Models.Entities.OwnerProduct", "OwnerProduct")
                        .WithMany("Searches")
                        .HasForeignKey("OwnerProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Baldan.Pricing.Application.Models.Entities.Period", "Period")
                        .WithMany("Searches")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Baldan.Pricing.Application.Models.Entities.SearchStatus", "SearchStatus")
                        .WithMany("Searches")
                        .HasForeignKey("SearchStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Baldan.Pricing.Application.Models.Entities.ThirdProduct", "ThirdProduct")
                        .WithMany("Searches")
                        .HasForeignKey("ThirdProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Baldan.Pricing.Application.Models.Entities.User", "User")
                        .WithMany("Searches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("OwnerProduct");

                    b.Navigation("Period");

                    b.Navigation("SearchStatus");

                    b.Navigation("ThirdProduct");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.SurveyEntry", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Models.Entities.Period", "Period")
                        .WithMany("SurveyEntries")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Baldan.Pricing.Application.Models.Entities.Search", "Search")
                        .WithMany("SurveyEntries")
                        .HasForeignKey("SearchId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Period");

                    b.Navigation("Search");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.ThirdProduct", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Models.Entities.Manufacturer", "Manufacturer")
                        .WithMany("ThirdProduct")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Baldan.Pricing.Application.Models.Entities.OwnerProduct", "OwnerProduct")
                        .WithOne()
                        .HasForeignKey("Baldan.Pricing.Application.Models.Entities.ThirdProduct", "OwnerProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");

                    b.Navigation("OwnerProduct");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.User", b =>
                {
                    b.HasOne("Baldan.Pricing.Application.Models.Entities.Profile", "Profile")
                        .WithMany("Users")
                        .HasForeignKey("Profileid")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.Family", b =>
                {
                    b.Navigation("OwnerProducts");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.Manufacturer", b =>
                {
                    b.Navigation("ThirdProduct");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.OwnerProduct", b =>
                {
                    b.Navigation("Searches");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.Period", b =>
                {
                    b.Navigation("Searches");

                    b.Navigation("SurveyEntries");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.Profile", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.Search", b =>
                {
                    b.Navigation("SurveyEntries");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.SearchStatus", b =>
                {
                    b.Navigation("Searches");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.State", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.ThirdProduct", b =>
                {
                    b.Navigation("Searches");
                });

            modelBuilder.Entity("Baldan.Pricing.Application.Models.Entities.User", b =>
                {
                    b.Navigation("Searches");
                });
#pragma warning restore 612, 618
        }
    }
}
